### ISSUE TITLE
Winners 방법론 이해

### ISSUE THREAD

**Issue by NoSyu** [NoSyu/FakeNewsChallenge2018#2]
챌린지 이후 1~3등 팀들은 각자 본인 방법론에 대한 설명을 코드와 함께 올렸습니다.

- https://github.com/Cisco-Talos/fnc-1
- https://github.com/hanselowski/athene_system
- https://github.com/uclmr/fakenewschallenge
- [작년 DDS 1기 FNC결과물](https://github.com/eliceio/fakenewsdetect)

이에 한 번 어떠한 방법론을 사용하였는지, 어떤 아이디어가 있었는지를 살펴봐주세요.

최소 보고서를 읽은 후 7월 24일에 얘기를 나누면 좋겠습니다.

**Comment by NoSyu** [comment]
일주일 더 연장하겠습니다.

**Comment by hutch24** [comment]
1주차 중간발표 및 지난해 우승 팀 분석 ppt링크(작성중)
https://goo.gl/ox2wGj

**Comment by mojoblue** [comment]
3등 모델은 기존 코드를 실행시켜 보았으며 
2등 모델과 1등 모델은 실행 환경의 차이 때문에 모델 분석 후
분석에 기반해 구현해 볼 예정입니다.
2등의 기존 모델은 분석이 완료되었고 우승 팀 분석 PPT에 업로드 해 놓았습니다.
최대한 빠른 시간 내에 1등 팀 분석을 완료해 분석 내용을 다음 주에 알려드릴 수 있도록 하겠습니다.

**Comment by hutch24** [comment]
CNN을 사용하여 한글로 가짜뉴스 탐지를 시도한 논문이 있어서 참고가 될까 싶어 올려봅니다.
-  딥러닝 기법을 이용한 가짜뉴스 탐지-2018 정보처리학화 춘계 학술대회 1등 수상 논문 [GitHub링크](https://github.com/2alive3s/Fake_news)
- [논문 및 발표자료 ppt](https://blog.naver.com/manadra/221292439404)

**Comment by hutch24** [comment]
2등팀(team Athene) 2018 새로운 모델-
    **A Retrospective Analysis of the Fake News Challenge Stance Detection Task 분석**
- [논문 링크](https://arxiv.org/pdf/1806.05180.pdf)
- [분석 PPT링크](https://docs.google.com/presentation/d/1oN-t9NIjRXi9FIbrl4f564dy-fepIYwLzlVqJv3ofrk/edit?usp=sharing) (제작중)

**Comment by mojoblue** [comment]
## 모델 구현 보고1 - 18.08.06
2등팀 논문 모델이 아닌 기존 모델(MLP)의 TF-IDF feature를 이용한 모델 구현을 완료했습니다. 
Train data만을 이용해 모델을 학습했고 10-fold validation을 시행했습니다.

||   agree   | disagree  |  discuss  | unrelated |
|------|------|------|------|------|
|   agree   |   3114    |    57     |    106    |    30     |
| disagree  |    62     |    673    |    17     |     3     |
|  discuss  |    74     |    18     |   7862    |    48     |
| unrelated |    30     |     5     |    55     |   32821   |

Score: 19937.75 out of 20291.75	(98.25544864292138%)

confusion matrix에서 가로축은 모델이 예측한 값, 세로축은 실제 값입니다.
10개의 모델의 예측 결과를 scoring한 값이며 자세한 코드는 코드 정리 후 commit할 예정입니다. - 1시간 남짓 소요

##추후 진행할 계획들
- 코드 정리 후 commit
- test data로 test
- 다른 feature를 이용해 결과 비교
- 1등 팀 모델 구현

**Comment by mojoblue** [comment]
# 3등 팀 모델 실행 및 평가 결과 - 18.08.16

|           |   agree   | disagree  |  discuss  | unrelated | precision |
|------|------|------|------|------|------|
|   agree   |    838    |    12     |    939    |    114    |  0.4404   |
| disagree  |    179    |    46     |    356    |    116    |  0.0660   |
|  discuss  |    523    |    46     |   3633    |    262    |  0.8138   |
| unrelated |    53     |     3     |    330    |   17963   |  0.9790   |
|  recall   |  0.5261   |  0.4299   |  0.6909   |  0.9733   |           |

Accuracy :  0.8845866288907253

F1 macro: 57.934% 
F1 agree: 47.941% 
F1 disagree: 11.443% 
F1 discuss: 74.738% 
F1 unrelated: 97.614% 

Score: 9521.5 out of 11651.25	(81.72084540285377%)

**Comment by mojoblue** [comment]
## 모델 구현 보고 - 2018.08.20
1등 모델의 방식인 XGBoost 모델의 성능이 좋아 해당 방식을 이용해 성능을 향상시키는 시도를 하고 있는 중입니다.

사용 Feature : TF-5000 with cosine sim, TF-IDF-5000 with cosine sim

|           |   agree   | disagree  |  discuss  | unrelated | precision |
|------|------|------|------|------|------|
|   agree   |    849    |     1     |    762    |    291    |  0.4461   |
| disagree  |    180    |     2     |    256    |    259    |  0.0029   |
|  discuss  |    673    |     2     |   3026    |    763    |  0.6779   |
| unrelated |    68     |     0     |    350    |   17931   |  0.9772   |
|  recall   |  0.4797   |  0.4000   |  0.6887   |  0.9318   |           |

F1 macro: 52.629% 
F1 agree: 46.229% 
F1 disagree: 0.570% 
F1 discuss: 68.322% 
F1 unrelated: 95.395% 

Score: 8828.25 out of 11651.25	(75.77084003862247%)

**Comment by mojoblue** [comment]
# 모델 구현 보고3  - 2018.08.28
- #### XGBoost 모델과 Stacked GRU 모델을 결합해 사용한 결과를 보고드립니다.

- #### XGBoost 사용 Feature : TF, TF-IDF cos, SVD cos 100, NMF cos 200, Glove 200D
- #### GRU 사용 Feature : Glove 50D
- #### 모델 가중치 비율은 XGBoost 0.7, Stacked GRU 0.3 입니다.
- #### FNC Score의 결과는 3등팀의 점수인 81.7%만을 따라잡았습니다.

|           |   agree   | disagree  |  discuss  | unrelated | precision |
|------|------|------|------|------|------|
|   agree   |    661    |     9     |   1136    |    97     |  0.3473   |
| disagree  |    197    |     7     |    409    |    84     |  0.0100   |
|  discuss  |    429    |     6     |   3868    |    161    |  0.8665   |
| unrelated |    75     |     2     |    461    |   17811   |  0.9707   |
|  recall   |  0.4853   |  0.2917   |  0.6585   |  0.9812   |           |

F1 macro: 53.713% 
F1 agree: 40.490% 
F1 disagree: 1.942% 
F1 discuss: 74.831% 
F1 unrelated: 97.589% 

Score: 9535.25 out of 11651.25	(81.83885849157815%)

**Comment by NoSyu** [comment]
https://stats.stackexchange.com/questions/18891/bagging-boosting-and-stacking-in-machine-learning
https://en.wikipedia.org/wiki/Ensemble_learning#Stacking

**Comment by mojoblue** [comment]
# 보고3의 모델에서 Logistic regression stacking을 이용한 실험 결과 보고 - 2018.08.29

- #### agree는 400개, disagree는 71개, unrelated는 233개 정도 더 잘 맞추었으나 discuss에서 1600여개를 맞추지 못하는 결과가 나왔습니다.

|           |   agree   | disagree  |  discuss  | unrelated |  recall   |
|------|------|------|------|------|------|
|   agree   |   1001    |    132    |    439    |    331    |  0.5260   |
| disagree  |    331    |    78     |    101    |    187    |  0.1119   |
|  discuss  |   1307    |    293    |   2254    |    610    |  0.5049   |
| unrelated |    114    |    10     |    192    |   18033   |  0.9828   |
| precision |  0.3636   |  0.1520   |  0.7549   |  0.9411   |           |

F1 macro: 53.138% 
F1 agree: 42.998% 
F1 disagree: 12.893% 
F1 discuss: 60.510% 
F1 unrelated: 96.150% 

Score: 8492.0 out of 11651.25	(72.88488359618067%)
