### ISSUE TITLE
Repo를 닫을까 합니다.

### ISSUE THREAD

**Issue by NoSyu** [NoSyu/FakeNewsChallenge2018#32]
안녕하세요.
Repo를 정리하다보니 여기 repo의 security alert이 여러 있네요.
https://github.com/NoSyu/FakeNewsChallenge2018/security/dependabot
아마 앞으로도 업데이트가 되지 않을 것 같기에 repo를 닫을까 생각합니다.
하지만 이 repo는 같이 한 분들이 여러 계시기에 여러분들의 의견/허락을 구하고자 합니다.
감사합니다.

**Comment by NoSyu** [comment]
의견을 여기 코멘트로 적어주시면 감사 드리겠습니다.

**Comment by mojoblue7** [comment]
네. 저는 repo 닫는 의견에 동의합니다.

**Comment by GoodLuckDay** [comment]
저도 repo 닫는 의견에 동의합니다.

**Comment by NoSyu** [comment]
두 분 의견 감사합니다.

그럼 일단 repo를 닫도록 하겠습니다.

혹시 필요하시다면 언제라도 연락주세요.
