### ISSUE TITLE
추가 데이터 크롤링

### ISSUE THREAD

**Issue by NoSyu** [NoSyu/FakeNewsChallenge2018#4]
현재 데이터는 headline과 body만 있습니다.
따라서 해당 기사들의 페이지를 접속하여 추가 데이터를 가져오겠습니다.

**Comment by Skm1221** [comment]
https://newsapi.org/

**Comment by mojoblue** [comment]
2등 모델 논문 survey를 통해 알아낸 내용을 공유해 드립니다.
FNC에서 http://www.emergent.info/ 에 있는 데이터를 이용한 것 같습니다.
해당 사이트에 관련 태그와 기사와 연결된 사이트들, share count, stance 정보 등이 있습니다.
크롤링 하실 때 참고하시면 도움이 될 것 같습니다.

- 관련 논문 : 
Emergent: a novel data-set for stance classification ( http://www.aclweb.org/anthology/N16-1138 )
A Retrospective Analysis of the Fake News Challenge Stance Detection Task ( https://arxiv.org/pdf/1806.05180.pdf )

**Comment by Skm1221** [comment]
column1: headline
column2: body_id
column3 ~ 12: 구글 검색 결과 순위로 `title, url`의 형식으로 저장
