### ISSUE TITLE
추가 데이터 분석

### ISSUE THREAD

**Issue by NoSyu** [NoSyu/FakeNewsChallenge2018#5]
수집된 추가 데이터에 대한 분석이 있어야겠습니다.
어떤 feature가 있을지 어떻게 이를 추출할지 등

**Comment by Skm1221** [comment]
https://newsapi.org/

**Comment by GoodLuckDay** [comment]
크롤링 한 데이터들 중에 Unique URL 선출 및 최상위 HOME URL parsing

선출 기준
- Youtube, Git, Blog, Cafe, Pdf 이외의 URL 선택

- 기존의 있던 약 10개정도의 후보중 위의 조건에 부합하지 않는 3개 선택

- 편집거리 알고리즘을 사용하여 가장 Cost가 낮은 headline을 가진 URL 선정

**Comment by mojoblue** [comment]
disagree를 agree로 예측한 데이터들을 모아 놓았습니다.
파일의 수는 191개이고 인코딩은 utf-8을 이용하였습니다.
기본적인 에디터로 읽으실 수 있을 것이라고 생각됩니다.
다운로드 링크 : https://drive.google.com/file/d/1o8e5wy_y6XLHNK3_Xz5KFyi2vHlxHCEC/view?usp=sharing
