### ISSUE TITLE
주 단위 진행 계획

### ISSUE THREAD

**Issue by hutch24** [NoSyu/FakeNewsChallenge2018#6]
**최종발표 : 9월 4일(화)**

2주 차 7/25 ~ 7/31 (D-6주)
- [x] 2017FNC 입상 팀 모델 분석 [PPT링크](https://goo.gl/pt3pH7)
- [x] 메타 데이터 크롤링 코드 작성

3주 차 8/1 ~ 8/7 (D-5주)
- [x] 입상자 팀 모델 구현
- [x] unrelated 데이터 제외한 메타 데이터 크롤링 실행
- [ ] 메타 데이터 분석

4주 차 8/8 ~ 8/14 (D-4주)

5주 차 8/15 ~ 8/21 (D-3주)

6주 차 8/22 ~ 8/28 (D-2주)

7주 차 8/29 ~ 9/4 (D-1주)

**Comment by mojoblue** [comment]
PPT링크가 잘못되어 있는 것 같습니다. 수정 부탁드립니다.
